### ISSUE TITLE
Bug - Bounds parameter lat/lng reversed

### ISSUE THREAD

**Issue by cohenlea** [moberwasserlechner/jopencage#27]
Should create the 'bounds' parameter as: min lng, min lat, max lng, max lat instead of: min lat, min lng, max lat, max lng

**Comment by cohenlea** [comment]
Also changed the order of the parameters in the setBounds() method to match the boundsSTr parameter to avoid confusion.

**Comment by moberwasserlechner** [comment]
Fixed with PR #28. Thx
