### ISSUE TITLE
Add "add_request" parameter

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/jopencage#3]
For forward and reverse requests.

This was added on Dec 10, 2015. 

```
"rate" : {
      "limit" : 2500,
      "remaining" : 2390,
      "reset" : 1496102400
   },
   "request" : {
      "abbrv" : 0,
      "add_request" : 1,
      "autocomplete" : 0,
      "format" : "json",
      "key" : "YOUR_API_KEY",
      "language" : "en",
      "limit" : 10,
      "min_confidence" : 0,
      "no_annotations" : 0,
      "no_dedupe" : 0,
      "no_record" : 0,
      "only_nominatim" : 0,
      "pretty" : 1,
      "query" : "41.40139 2.12870",
      "version" : "v1"
   },
   "results" : [
```

**Comment by moberwasserlechner** [comment]
For this I will have to break and/or refactor a few things. I postpone this change.

**Comment by moberwasserlechner** [comment]
I think the this task not needed at all. It would simply add the request parameters to the response but a user already has the request parameters. So I guess it's a feature nobody would use.

**Comment by freyfogle** [comment]
Hi Michael,

I thought this as well, but we had numerous users request this feature (why we added it). Basically they argued it was simple for them to just get a response and dump the whole thing in a database and thus always have the request parameters and the response in a single place. Über Geschmack lässt sich nicht streiten. 

But totally up to you, it is not a widely used parameter

**Comment by moberwasserlechner** [comment]
I reopen it. Contributions are welcome. ;)

**Comment by cohenlea** [comment]
I'm happy to take a look. @moberwasserlechner can you point me in the direction of what you think might break or need to be refactored so I know what to watch out for?

**Comment by moberwasserlechner** [comment]
hey, I dont really know anymore. I guess I meant to refactor the requests in form so i can reuse the requesting classes or their members in the response as well. 

Unfortunately I do not have the time to digg deeper because I have to focus on other stuff at least for next few weeks.

**Comment by cohenlea** [comment]
Ok no prob! I'll check it out.

**Comment by moberwasserlechner** [comment]
I'm closing this as I have no idea what I wanted to do in this task anymore ;)
