### ISSUE TITLE
httpclient libs

### ISSUE THREAD

**Issue by adminvas** [moberwasserlechner/jopencage#30]
can you please inform me which httpclient lib your library needs ?
So far all libs I tried are giving me an error.

best regards
Vassilis

**Comment by moberwasserlechner** [comment]
This lib currently uses `org.apache.httpcomponents:httpclient:4.5.6`. You should look at the `dependencies` section in the `build.gradle`. This is a transitive dependency and by using a dependency management tool like Maven, Gradle, Ivy you dont need to worry about it.
