### ISSUE TITLE
unknown enum constant Include.NON_NULL and Failed to load class “org.slf4j.impl.StaticLoggerBinder”

### ISSUE THREAD

**Issue by alessandroquirile** [moberwasserlechner/jopencage#36]
I'm following the official OpenCage Geocoder Java Tutorial.

I've add JOpenCage dependency as it says using these gradle instructions:

repositories {
  jcenter()
}

dependencies {
  compile ("com.byteowls:jopencage:replace.with.version")
}
For this reason, my Gradle project build.gradle file will be:

build.gradle file

plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile("com.byteowls:jopencage:1.3.0")
}
This is my Main class for testing forward and reverse geocoding:

public class Main {
    public static void main(String[] args) {

         forwardGeocoding();
    }

    public static void forwardGeocoding() {
        JOpenCageGeocoder jOpenCageGeocoder = new JOpenCageGeocoder("XXX");

        JOpenCageReverseRequest request = new JOpenCageReverseRequest(41.40015, 2.15765);
        request.setLanguage("es"); // prioritize results in a specific language using an IETF format language code
        request.setNoDedupe(true); // don't return duplicate results
        request.setLimit(5); // only return the first 5 results (default is 10)
        request.setNoAnnotations(true); // exclude additional info such as calling code, timezone, and currency
        request.setMinConfidence(3); // restrict to results with a confidence rating of at least 3 (out of 10)

        JOpenCageResponse response = jOpenCageGeocoder.reverse(request);

        // get the formatted address of the first result:
        String formattedAddress = response.getResults().get(0).getFormatted();

        System.out.println(formattedAddress);
    }
}
and this is the output (note that formattedAddress is printed successfully but there are some warnings and errors):

14:23:10: Executing task 'Main.main()'...

Task :compileJava UP-TO-DATE Task :processResources NO-SOURCE Task :classes UP-TO-DATE

Task :Main.main() Travessera de Gràcia, 142, 08001 Barcelona, España

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s 2 actionable tasks: 1 executed, 1 up-to-date SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 14:23:12: Task execution finished 'Main.main()'.

- We should fix these errors.

**Comment by moberwasserlechner** [comment]
This build message is more a warning than an error. It does not prevent anyone using the lib. But I'm happy to accept a PR for this.

See https://github.com/moberwasserlechner/jopencage#fix-a-bug-or-create-a-new-feature

**Comment by moberwasserlechner** [comment]
I do it myself in #39
