### ISSUE TITLE
JOpenCageComponents should contain unmapped objects of a _type key and _category

### ISSUE THREAD

**Issue by Dexilon** [moberwasserlechner/jopencage#37]
See the image below:
![1](https://user-images.githubusercontent.com/33017717/112868059-eaf2d900-90bb-11eb-844f-94cccb9e6d4b.png)

Right now fields like _category and in this case "leisure" are not mapped to the JOpenCageResponse:
![2](https://user-images.githubusercontent.com/33017717/112868231-1bd30e00-90bc-11eb-9066-e9035228f881.png)

I think that for that those fields or any other key of _type  should be included for the easier manipulation of the formatted string in the response.
Currently the raw JSON object in the response contains all the vital components for the custom formation of the string, but the JOpenCageComponents does not contain, for example, a field "leisure" IF there is a "_type" : "leisure" , so that field cannot be mapped from JSON to the JOpenCageResponse.

Here is the example :
"coordinates": [
            16.407438398213937,
            48.172555994664336
        ]
 
formatted = “FC Mariahilf, Leberstraße 84, 1110 Wien, Österreich”
We want to, for example, be able to remove “FC Mariahilf”. So I think that if we could add a HashMap field "unmappedFields" for all the dynamic fields that are currently not being mapped to the JOpenCageComponents response, which adds a tad more flexibility to the code..

**Comment by Dexilon** [comment]
Since I am not allowed to push the changes to create a PR, here is a solution:

Just add these lines of code in JOpenCageComponents
`    Map<String, Object> unmappedFields = new LinkedHashMap<>();

    @JsonAnySetter
    void setUnmappedFields(String key, Object value) {
        unmappedFields.put(key, value);
    }
    public Map<String, Object> getUnmappedFields() { return unmappedFields; }`

**Comment by moberwasserlechner** [comment]
Hi, 

I checked the docs for creating PRs and it is missing one part, that I though is obvious.

You have to clone the this repo.

I will add it to the README.

BR

**Comment by moberwasserlechner** [comment]
https://github.com/moberwasserlechner/jopencage#contribute
