### ISSUE TITLE
Migrate Lib to Maven Central

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/jopencage#41]
As I wanted to release 1.4.0 to Bintray the website informed me that they're sun setting their services.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

![image](https://user-images.githubusercontent.com/1049938/113411300-b5006e00-93b5-11eb-89a4-d6a7318f96dc.png)

Their UI is only partly, working as they have already shutdown some services.

**Comment by moberwasserlechner** [comment]
Migration https://blog.sonatype.com/what-publishers-need-to-know-about-migrating-from-jcenter-/-bintray-to-the-central-repository

**Comment by moberwasserlechner** [comment]
I will trigger the publishing on creating a release on GH. That works well for GH Packages on private projects and should be fine as well for Maven Central.

**Comment by moberwasserlechner** [comment]
Started validation process in SonaType Jira. According to their info it will take ~2 business days to check my inquiry.

**Comment by moberwasserlechner** [comment]
https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-67146

**Comment by filnko** [comment]
Hi Michael, sorry to be pushing here but do you think it would be possible to release via Maven central this week? We have a release on Monday and would be eager to get the PR #38 in.
Thanks and liebe Grüße aus Wien.

**Comment by moberwasserlechner** [comment]
Trying to push the maintainer of an open source project would be a really good idea indeed 😂. 

Anyway when time is short, my paid projects are preferred. I'm a freelancer after all. So I'm sure you understand.

Maybe I find the time todo it tomorrow but I can't say how long it takes Sonatype to activate the sync to Maven Central. 

BR and Liebe Grüße aus Graz

ps If your build and deployment does not fully depend on CI. You can always publish the project locally and build it from 'mavenLocal'.

**Comment by moberwasserlechner** [comment]
Maybe I have to clarify one thing: 

I have no business relations to "OpenCage". I simply build a lib a while ago but do not actively use it in my own projects anymore.

**Comment by moberwasserlechner** [comment]
Signing Resources:

* https://docs.gradle.org/current/userguide/signing_plugin.html#signing_plugin
* https://docs.github.com/en/github/authenticating-to-github/checking-for-existing-gpg-keys

**Comment by moberwasserlechner** [comment]
For local publishing the signing information must be added to `~/.gradle/gradle.properties`

```
# Maven Signing
#  gpg --list-secret-keys --keyid-format LONG
MAVEN_SIGNING_KEY_ID=<replace_with_last_8_chars_of_key_id>
# armored private key
# gpg --armor --export-secret-key <KEY_ID>
MAVEN_SIGNING_KEY=-----BEGIN PGP PRIVATE KEY BLOCK-----\n \
multi\n \
line\n \
property\n \
-----END PGP PRIVATE KEY BLOCK-----
# key pair passphrase
MAVEN_SIGNING_PASSWORD=<replace_with_passphrase>
```

Local publish command.
```
./gradlew -Pversion=x.x.x publishToMavenLocal
```

**Comment by moberwasserlechner** [comment]
I do the release locally as GH actions does not find the gpg task.

**Comment by moberwasserlechner** [comment]
Maven Central also needed my Public Key to verify the signature. 

Signing docs: https://central.sonatype.org/publish/requirements/gpg/

**Comment by moberwasserlechner** [comment]
Release was done in Sonatype Nexus. As this is the first component on Maven Central Sonatype needs to activate the sync before the lib is visible.

**Comment by moberwasserlechner** [comment]
Sync is active and already at https://repo1.maven.org/maven2/com/byteowls/jopencage/1.4.0/

It should be available on search.maven.org within 2 hours.
